name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Build with `svg`
      run: cargo build --verbose -F svg
    - name: Build with `image`
      run: cargo build --verbose -F image
    - name: Build examples
      run: cargo build --examples --all-features
    - name: Build benchmarks
      run: cargo build --benches
    - name: Run tests
      run: cargo test --verbose -F svg,image
